name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.event.repository.name }}-build-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        timeout-minutes: 5

      - uses: actions/setup-node@v3
        timeout-minutes: 5
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: npm ci
        timeout-minutes: 5

      - run: npm run build
        timeout-minutes: 15
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Install lftp
        if: github.ref == 'refs/heads/master'
        timeout-minutes: 2
        run: sudo apt-get install lftp

      - name: Sync via FTP
        if: github.ref == 'refs/heads/master'
        timeout-minutes: 120
        run: lftp ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOSTNAME }} -e "set ftp:ssl-allow off; mirror -v -R --only-newer ./dist /; quit"
